### PR TITLE
ML-350 Descriptive Stats

### PR DESCRIPTION
**Pull request by ghost**
Definitions added to the field aggregates module for:
- N-Histograms - binned counts of each variable in a NumericField
- Pearson correlation matrix (all pairs of variables)
- Spearman's rank correlation matrix
- Kendall's rank correlation matrix
- Generalized Spearman^2 for variable importance (see Frank Harrell's Hmisc package on CRAN)

Signed-off-by: Timothy Esler <timothy.esler@lexisnexisrisk.com>

### CODE REVIEW

**Comment by ghost** [comment]
This pull request ensures that most of what is mentioned in the description of https://track.hpccsystems.com/browse/ML-350 is available in the FieldAggregates module for NumericFields. I haven't implemented anything for DiscreteFields.

**Comment by johnholt** [comment]
@rogerdev @emuharemagic  I'll review this week, but I would appreciate it if you guys could review as well.

**Comment by johnholt** [comment]
@RogerDev @emuharemagic these look OK except that they will have problems with really large datasets.  What do you think?

**Comment by johnholt** [comment]
@richard this is good to merge

**Pull request merged**
