### PR TITLE
ML-423 In ML_Core.Analysis.Classification.Accuracy, PoDE sometimes co…

### PR DESCRIPTION
**Pull request by RogerDev**
…mes back with a huge integer rather than a small negative value

Changed to use UNSIGNED4 for counters rather than UNSIGNED

Signed-off-by: Roger Dev <Roger.Dev@LexisNexisRisk.com>

### CODE REVIEW

**Comment by RogerDev** [comment]
@richardkchapman This is ready for review and merge

**Comment by richardkchapman** [comment]
Not sure why this change would fix the described symptom...

**Comment by johnholt** [comment]
Just my 2cents, but this does not sound like the right solution.  An UNSIGNED is an 8 byte integer.  Making it 4 bytes makes it wrap sooner.  

John Holt

**Comment by RogerDev** [comment]
Per Gavin, subtracting two UNSIGNED4s will automatically treat them as signed, while UNSIGNED8 (UNSIGNED) cannot be treated as signed because no signed integer can hold an arbitrary UNSIGNED8.
Per C++ rules.  When I subtracted the two UNSIGNED attributes, with the second larger than the first, the result was a huge UNSIGNED rather than a small negative number.  None of the counts should be > 4B, so there is not harm in using the UNSIGNED4.  I had previously casted the UNSIGNED to INTEGER before the subtraction, but this seemed cleaner.

**Comment by richardkchapman** [comment]
@ghalliday Can you comment?

**Comment by ghalliday** [comment]
@RogerDev I think your original solution was probably more correct (either that, or casting the result of the subtraction to an integer).
If the values cannot exceed 4B then it should not cause any earlier wrapping (since they are converted to INTEGER before subtraction), but it is a bit of an obscure fix to use smaller width unsigned to ensure a difference is signed.  If you are going to change the type then I would change it to an INTEGER.

**Comment by RogerDev** [comment]
@richardkchapman 
Unless you feel strongly about it, I'd rather leave the code as is, to avoid re-testing.  The code works, and is reasonable as written (I would have written it that way initially if I knew about the UNSIGNED8 limitation). Admittedly, as a fix, the mechanics were a bit obscure.

**Comment by richardkchapman** [comment]
@ghalliday I will leave the decision to you

**Comment by ghalliday** [comment]
It isn't really the correct fix, but since it has been tested, and the field will not go above 4B, so there will not be an overflow issue I will merge it as-is.

**Pull request merged**
