### PR TITLE
ML-351 Normal, T, and Chi square distributions

### PR DESCRIPTION
**Pull request by johnholt**
The Cumulative Distribution Function (CDF) in Percentage Point Function (inverse of the CDF) for the Standard Normal, Student's T, and Chi Squared distributions.  A test function to compare the reslts to the equivalent function in scipy is included.

Signed-off-by: johnholt <john.d.holt@lexisnexis.com>

### CODE REVIEW

**Comment by johnholt** [comment]
@rogerdev @ghalliday  This is the new home for the Distributions CDF and PPF functions for the Normal, T, and Chi**2 distributions.

**Comment by johnholt** [comment]
Updated version number in Bundle.ecl file for dependency check.

**Comment by johnholt** [comment]
@rogerdev  code review still needed.    @ghalliday  code review of embedded C++ code still needed.

**Comment by ghalliday** [comment]
@johnholt how does this fit in with the PR for the logistic regression?  It looks like the functions are very similar/the same.  Will the logistic regression switch over to using these functions?

**Comment by johnholt** [comment]
It is the code.  Once this is in Core, I'll remove the version from Logistic Regression.

**Comment by ghalliday** [comment]
ok, see comments on the code in the other pR

**Comment by johnholt** [comment]
@ghalliday  Code review changes made.

**Comment by johnholt** [comment]
@richardkchapman  I think that this one is now good to go.

**Pull request merged**
